### ISSUE TITLE
coffeescript 2 with transpile + inlined source maps?

### ISSUE THREAD

**Issue by d9k** [gulp-community/gulp-coffee#91]
Please include configuration examples to README.md

**Comment by d9k** [comment]
I'm get error:

```
Error: Source map to be applied is missing the "file" property
    at assertProperty (/home/myuser/myproject/node_modules/vinyl-sourcemaps-apply/index.js:36:13)
    at applySourceMap (/home/myuser/myproject/node_modules/vinyl-sourcemaps-apply/index.js:15:3)
    at DestroyableTransform.transform [as _transform] (/home/myuser/myproject/node_modules/gulp-coffee/index.js:41:7)
    at DestroyableTransform.Transform._read (/home/myuser/myproject/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.
js:184:10)
```
My gulp task:

```
var gulp    = require('gulp'),
    coffee  = require('gulp-coffee'),
    sourcemaps = require('gulp-sourcemaps');

gulp.task('coffee', function(){
    gulp.src(config.coffeePath + '/**/*.coffee')
        .pipe(sourcemaps.init())
        .pipe(coffee({
          bare: true,
          transpile: {
            presets: [
              // Without any configuration options, babel-preset-env behaves exactly the same as babel-preset-latest (or babel-preset-es2015, babel-preset-es2016, and babel-preset-es2017 together).
              'env',
            ],
            plugins: [
              ["transform-react-jsx"]
            ],
          }
        }))
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest('./static/js'));
});
```

**Comment by shnam7** [comment]
I'm experiencing the same problem. Any progress on this?

**Comment by contra** [comment]
Does adding `sourceMap: true, inlineMap: true` to the options work? I think they changed this recently - if that fixes it I will update the module.

**Comment by phonowell** [comment]
just got the same problem, any one could help?

**Comment by brewster1134** [comment]
➕ 1️⃣

**Comment by yocontra** [comment]
Couple of pointers to help you all:

- Don't use gulp-sourcemaps directly anymore, sourcemaps are built into gulp 4 so you can just turn on sourcemaps in gulp.src
- Make sure you read the coffee-script docs on how to enable sourcemaps, then it should play nicely with the gulp sourcemap support

**Comment by brewster1134** [comment]
i guess my issue was more with just being able to transpile at all... gulp-coffee doesn't support the coffeescript's transpile feature. also, i was unable to get sourcemaps to work with gulp 4... i had to still use the gulp-sourcemaps plugin. i currently don't have my project in a state to test it ATM, but would be good to hear someone confirm it is actually working...

**Comment by nitely** [comment]
You can use `gulp-babel` instead of coffeescript transpile option.

Example:

```js
var gulp = require('gulp');
var babel = require('gulp-babel');
var coffee = require('gulp-coffee');

gulp.task('coffee', function() {
  gulp.src('./src/*.coffee', { sourcemaps: true })
    .pipe(coffee({bare: true}))
    .pipe(babel({presets: ['@babel/preset-env']}))
    .pipe(gulp.dest('./public/', { sourcemaps: true }));  // change to , { sourcemaps: '.' } to generate external sourcemaps
});
```
 The transpile option should work, but it does not at the moment.
